### ISSUE TITLE
Pinche ardillita hermosa y preciosa y fea.

### ISSUE THREAD

**Issue by Axol44** [ggzor/Programacion2-Practica6#1]
Tienes que hacer las pruebas en filtrar, los acentos. 
https://github.com/ggzor/Programacion2-Practica6/blob/e9a64f644c8851a937f016e55444cb8cb742ccec/src/main/java/Analizador.java#L23-L32

**Comment by ggzor** [comment]
Pinche paquetito bonito e inteligente.

**Comment by ggzor** [comment]
Pinche paquetito bonito e inteligente.
